# @no-reject-unauthorized

@api = https://localhost:7025

###
POST {{api}}/additem
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "description": "a",
  "image": "a",
  "price": 123,
  "itemId": "9b1c44e5-5711-450a-8fb9-4fc5360ca1a9",
  "productId": "2e03274e-486b-4a44-b91b-2fa549c72767"
}

###
@cartId = af568328-19cd-4916-9e79-29a67de8a0cc

###
@productId = 2e03274e-486b-4a44-b91b-2fa549c72767

###
POST {{api}}/additem/{{cartId}}
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "description": "a",
  "image": "a",
  "price": 123,
  "itemId": "9b1c44e5-5711-450a-8fb9-4fc5360ca1a9",
  "productId": "2e03274e-486b-4a44-b91b-2fa549c72767"
}


###
GET {{api}}/{{cartId}}/cartitems
Accept: application/json


###
POST {{api}}/removeitem/{{cartId}}
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "itemId": "9b1c44e5-5711-450a-8fb9-4fc5360ca1a9"
}

###
POST {{api}}/clearcart/{{cartId}}
Accept: application/json



###
POST {{api}}/simulate-inventory-external-event-translation/
Content-Type: application/json; charset=utf-8

{
  "productId": "{{productId}}",
  "inventory": 15
}

###
GET {{api}}/inventories/{{productId}}
Accept: application/json

###
POST {{api}}/changeprice/{{productId}}
Content-Type: application/json; charset=utf-8

{
  "oldPrice": 100,
  "newPrice": 15
}

###
GET {{api}}/cartwithproducts/{{productId}}
Accept: application/json

###
POST {{api}}/archiveitem/{{cartId}}

###
POST {{api}}/submitcart/{{cartId}}
Accept: application/json
Content-Type: application/json; charset=utf-8

{
}

###
POST {{api}}/publishcart/{{cartId}}
Accept: application/json
Content-Type: application/json; charset=utf-8

{
}
